package com.capitalone.dashboard.status;

public enum AutoDiscoverAuditStatus {
    AUTO_DISCOVER_EVIDENCES_FOUND,
    AUTO_DISCOVER_EVIDENCES_NOT_FOUND,
    AUTO_DISCOVER_CODE_REPO_URLS_FOUND,
    AUTO_DISCOVER_BUILD_EVIDENCES_FOUND,
    AUTO_DISCOVER_SECURITY_SCAN_EVIDENCES_FOUND,
    AUTO_DISCOVER_DEPLOY_EVIDENCES_FOUND,
    AUTO_DISCOVER_LIBRARY_POLICY_EVIDENCES_FOUND,
    AUTO_DISCOVER_FUNCTIONAL_TEST_EVIDENCES_FOUND,
    AUTO_DISCOVER_ARTIFACT_EVIDENCES_FOUND,
    AUTO_DISCOVER_STATIC_CODE_EVIDENCES_FOUND,
    AUTO_DISCOVER_FEATURE_EVIDENCES_FOUND,
    AUTO_DISCOVER_PERF_TEST_EVIDENCES_FOUND;
}
