package com.capitalone.dashboard.status;

public enum InfrastructureAuditStatus {
    INFRA_SCAN_COMP_OK,
    INFRA_SCAN_COMP_HIGH,
    INFRA_SCAN_COMP_CRITICAL,
    INFRA_SEC_SCAN_BA_OK,
    INFRA_SEC_SCAN_BA_CRITICAL,
    INFRA_SEC_SCAN_BA_HIGH,
    INFRA_SEC_SCAN_COMP_NOT_FOUND,
    INFRA_SEC_SCAN_BA_NOT_FOUND,
    UNAVAILABLE;
}
