package com.capitalone.dashboard.status;

public enum InfrastructureAuditStatus {
    INFRA_SCAN_BUSS_COMP_OK,
    INFRA_SCAN_BUSS_COMP_HIGH,
    INFRA_SCAN_BUSS_COMP_CRITICAL,
    INFRA_SEC_SCAN_BUSS_APP__OK,
    INFRA_SEC_SCAN_BUSS_APP_CRITICAL,
    INFRA_SEC_SCAN_BUSS_APP_HIGH,
    INFRA_SEC_SCAN_BUSS_COMP_NOT_FOUND,
    INFRA_SEC_SCAN_BUSS_APP_NOT_FOUND,
    UNAVAILABLE;
}
